//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorUsuarioService.Infra.SQL.ControleAcesso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControleAcesso.ControleAcessoSoap")]
    public interface ControleAcessoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecaPermissaoPorFuncionalidade", ReplyAction="*")]
        GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse ChecaPermissaoPorFuncionalidade(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecaPermissaoPorFuncionalidade", ReplyAction="*")]
        System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse> ChecaPermissaoPorFuncionalidadeAsync(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOperacoesPorFuncionalidade", ReplyAction="*")]
        GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse GetOperacoesPorFuncionalidade(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOperacoesPorFuncionalidade", ReplyAction="*")]
        System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse> GetOperacoesPorFuncionalidadeAsync(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChecaPermissaoPorFuncionalidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChecaPermissaoPorFuncionalidade", Namespace="http://tempuri.org/", Order=0)]
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody Body;
        
        public ChecaPermissaoPorFuncionalidadeRequest() {
        }
        
        public ChecaPermissaoPorFuncionalidadeRequest(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChecaPermissaoPorFuncionalidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idLdap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string funcionalidadeSigla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ipClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mensagemDeErroParam;
        
        public ChecaPermissaoPorFuncionalidadeRequestBody() {
        }
        
        public ChecaPermissaoPorFuncionalidadeRequestBody(string idLdap, string funcionalidadeSigla, string ipClient, string mensagemDeErroParam) {
            this.idLdap = idLdap;
            this.funcionalidadeSigla = funcionalidadeSigla;
            this.ipClient = ipClient;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChecaPermissaoPorFuncionalidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChecaPermissaoPorFuncionalidadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponseBody Body;
        
        public ChecaPermissaoPorFuncionalidadeResponse() {
        }
        
        public ChecaPermissaoPorFuncionalidadeResponse(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChecaPermissaoPorFuncionalidadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChecaPermissaoPorFuncionalidadeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensagemDeErroParam;
        
        public ChecaPermissaoPorFuncionalidadeResponseBody() {
        }
        
        public ChecaPermissaoPorFuncionalidadeResponseBody(bool ChecaPermissaoPorFuncionalidadeResult, string mensagemDeErroParam) {
            this.ChecaPermissaoPorFuncionalidadeResult = ChecaPermissaoPorFuncionalidadeResult;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperacoesPorFuncionalidadeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOperacoesPorFuncionalidade", Namespace="http://tempuri.org/", Order=0)]
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequestBody Body;
        
        public GetOperacoesPorFuncionalidadeRequest() {
        }
        
        public GetOperacoesPorFuncionalidadeRequest(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOperacoesPorFuncionalidadeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idLdap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string funcionalidadeSigla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ipClient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mensagemDeErroParam;
        
        public GetOperacoesPorFuncionalidadeRequestBody() {
        }
        
        public GetOperacoesPorFuncionalidadeRequestBody(string idLdap, string funcionalidadeSigla, string ipClient, string mensagemDeErroParam) {
            this.idLdap = idLdap;
            this.funcionalidadeSigla = funcionalidadeSigla;
            this.ipClient = ipClient;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOperacoesPorFuncionalidadeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOperacoesPorFuncionalidadeResponse", Namespace="http://tempuri.org/", Order=0)]
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponseBody Body;
        
        public GetOperacoesPorFuncionalidadeResponse() {
        }
        
        public GetOperacoesPorFuncionalidadeResponse(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOperacoesPorFuncionalidadeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ArrayOfString GetOperacoesPorFuncionalidadeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mensagemDeErroParam;
        
        public GetOperacoesPorFuncionalidadeResponseBody() {
        }
        
        public GetOperacoesPorFuncionalidadeResponseBody(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ArrayOfString GetOperacoesPorFuncionalidadeResult, string mensagemDeErroParam) {
            this.GetOperacoesPorFuncionalidadeResult = GetOperacoesPorFuncionalidadeResult;
            this.mensagemDeErroParam = mensagemDeErroParam;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControleAcessoSoapChannel : GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControleAcessoSoapClient : System.ServiceModel.ClientBase<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap>, GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap {
        
        public ControleAcessoSoapClient() {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControleAcessoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControleAcessoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap.ChecaPermissaoPorFuncionalidade(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request) {
            return base.Channel.ChecaPermissaoPorFuncionalidade(request);
        }
        
        public bool ChecaPermissaoPorFuncionalidade(string idLdap, string funcionalidadeSigla, string ipClient, ref string mensagemDeErroParam) {
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest inValue = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest();
            inValue.Body = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody();
            inValue.Body.idLdap = idLdap;
            inValue.Body.funcionalidadeSigla = funcionalidadeSigla;
            inValue.Body.ipClient = ipClient;
            inValue.Body.mensagemDeErroParam = mensagemDeErroParam;
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse retVal = ((GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap)(this)).ChecaPermissaoPorFuncionalidade(inValue);
            mensagemDeErroParam = retVal.Body.mensagemDeErroParam;
            return retVal.Body.ChecaPermissaoPorFuncionalidadeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse> GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap.ChecaPermissaoPorFuncionalidadeAsync(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest request) {
            return base.Channel.ChecaPermissaoPorFuncionalidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeResponse> ChecaPermissaoPorFuncionalidadeAsync(string idLdap, string funcionalidadeSigla, string ipClient, string mensagemDeErroParam) {
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest inValue = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequest();
            inValue.Body = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ChecaPermissaoPorFuncionalidadeRequestBody();
            inValue.Body.idLdap = idLdap;
            inValue.Body.funcionalidadeSigla = funcionalidadeSigla;
            inValue.Body.ipClient = ipClient;
            inValue.Body.mensagemDeErroParam = mensagemDeErroParam;
            return ((GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap)(this)).ChecaPermissaoPorFuncionalidadeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap.GetOperacoesPorFuncionalidade(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest request) {
            return base.Channel.GetOperacoesPorFuncionalidade(request);
        }
        
        public GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ArrayOfString GetOperacoesPorFuncionalidade(string idLdap, string funcionalidadeSigla, string ipClient, ref string mensagemDeErroParam) {
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest inValue = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest();
            inValue.Body = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequestBody();
            inValue.Body.idLdap = idLdap;
            inValue.Body.funcionalidadeSigla = funcionalidadeSigla;
            inValue.Body.ipClient = ipClient;
            inValue.Body.mensagemDeErroParam = mensagemDeErroParam;
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse retVal = ((GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap)(this)).GetOperacoesPorFuncionalidade(inValue);
            mensagemDeErroParam = retVal.Body.mensagemDeErroParam;
            return retVal.Body.GetOperacoesPorFuncionalidadeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse> GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap.GetOperacoesPorFuncionalidadeAsync(GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest request) {
            return base.Channel.GetOperacoesPorFuncionalidadeAsync(request);
        }
        
        public System.Threading.Tasks.Task<GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeResponse> GetOperacoesPorFuncionalidadeAsync(string idLdap, string funcionalidadeSigla, string ipClient, string mensagemDeErroParam) {
            GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest inValue = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequest();
            inValue.Body = new GerenciadorUsuarioService.Infra.SQL.ControleAcesso.GetOperacoesPorFuncionalidadeRequestBody();
            inValue.Body.idLdap = idLdap;
            inValue.Body.funcionalidadeSigla = funcionalidadeSigla;
            inValue.Body.ipClient = ipClient;
            inValue.Body.mensagemDeErroParam = mensagemDeErroParam;
            return ((GerenciadorUsuarioService.Infra.SQL.ControleAcesso.ControleAcessoSoap)(this)).GetOperacoesPorFuncionalidadeAsync(inValue);
        }
    }
}
