use TesteEntrevista
GO

IF EXISTS ( SELECT  *
            FROM    SYS.OBJECTS
            WHERE   OBJECT_ID = OBJECT_ID(N'PROC_CLIENTE_UPDATE')
                    AND TYPE IN ( N'P', N'PC' ) ) 
BEGIN
	DROP PROCEDURE PROC_CLIENTE_UPDATE;
END
GO

CREATE PROCEDURE PROC_CLIENTE_UPDATE
	@ID INT,
	@CPF varchar(15),
	@NOME  VARCHAR(100),
	@DATANASCIMENTO DATE,
	@TELEFONE VARCHAR(20),
	@EMAIL VARCHAR(50),

	@MATRICULA INT,
	@ATIVO BIT
AS
BEGIN
	
	SET NOCOUNT ON;
	SET XACT_ABORT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	BEGIN TRY
		
		BEGIN TRANSACTION;

		-- INSTRUÇÕES SQL -- INÍCIO

		DECLARE @IDPESSOA INT = (SELECT IDPESSOA FROM CLIENTE WHERE ID = @ID)


		EXEC PROC_PESSOA_UPDATE @IDPESSOA, @CPF, @NOME, @DATANASCIMENTO, @TELEFONE, @EMAIL;



		UPDATE [DBO].[CLIENTE]
		   SET [MATRICULA] = @MATRICULA
			  ,[ATIVO] = @ATIVO
			  ,[IDPESSOA] = @IDPESSOA
		 WHERE 
			ID = @ID

		-- INSTRUÇÕES SQL -- FIM
		
		IF @@TRANCOUNT > 0 COMMIT TRANSACTION;
		
	END TRY
	
	BEGIN CATCH
		
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
		
		DECLARE @ERRORMESSAGE NVARCHAR(4000);
		DECLARE @ERRORSEVERITY INT;
		DECLARE @ERRORSTATE INT;

		SELECT @ERRORMESSAGE = ERROR_MESSAGE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORSTATE = ERROR_STATE();

		RAISERROR (@ERRORMESSAGE,
				   @ERRORSEVERITY,
				   @ERRORSTATE
				   );
			
	END CATCH
END