use TesteEntrevista
GO

IF EXISTS ( SELECT  *
            FROM    SYS.OBJECTS
            WHERE   OBJECT_ID = OBJECT_ID(N'PROC_CLIENTE_SELECT_POR_CPF')
                    AND TYPE IN ( N'P', N'PC' ) ) 
BEGIN
	DROP PROCEDURE PROC_CLIENTE_SELECT_POR_CPF;
END
GO

CREATE PROCEDURE PROC_CLIENTE_SELECT_POR_CPF
	@CPF VARCHAR(15)
AS
BEGIN
	
	SET NOCOUNT ON;
	SET XACT_ABORT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	
	BEGIN TRY
		
		BEGIN TRANSACTION;

		SELECT
		   C.[ID]
		  ,C.[MATRICULA]
		  ,C.[ATIVO]
		  ,P.[ID] AS IDPESSOA
		  ,P.[CPF]
		  ,P.[NOME]
		  ,P.[DATANASCIMENTO]
		  ,P.[TELEFONE]
		  ,P.[EMAIL]
		FROM
			CLIENTE C
		INNER JOIN
			PESSOA P
		ON
			C.IDPESSOA = P.ID
		WHERE 
			P.[CPF] = @CPF;
		-- INSTRUÇÕES SQL -- FIM
		
		IF @@TRANCOUNT > 0 COMMIT TRANSACTION;
		
	END TRY
	
	BEGIN CATCH
		
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
		
		DECLARE @ERRORMESSAGE NVARCHAR(4000);
		DECLARE @ERRORSEVERITY INT;
		DECLARE @ERRORSTATE INT;

		SELECT @ERRORMESSAGE = ERROR_MESSAGE(),
			   @ERRORSEVERITY = ERROR_SEVERITY(),
			   @ERRORSTATE = ERROR_STATE();

		RAISERROR (@ERRORMESSAGE,
				   @ERRORSEVERITY,
				   @ERRORSTATE
				   );
			
	END CATCH
END